from minio.error import S3Error
